import Head from "next/head";
import { useRouter } from "next/router";
import Header from "../components/Header";
import Footer from "../components/Footer";

const privacy = () => {
  return (
    <div className="">
      <Head>
        <title>Cosmetics Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="privacy-main max-w-7xl mx-auto md:mx-20 lg:mx-40 px-8 sm:px-16 py-10 md:py-20 bg-white">
        <section>
          <h1 className="text-2xl md:text-4xl mb-10 bg-gold-100 text-white p-4">
            プライバシーポリシー
          </h1>
          <div>
            Cosmetics
            collection（以下、「当サイト」と言います。）では、お客様からお預かりする個人情報の重要性を強く認識し、個人情報の保護に関する法律、その他の関係法令を遵守すると共に、以下に定めるプライバシーポリシーに従って、個人情報を安全かつ適切に取り扱うことを宣言いたします。
          </div>
          <h2 className="privacy-h2 text-xl md:text-2xl mt-10 mb-5 p-3">
            個人情報の定義
          </h2>
          <div>
            本プライバシーポリシーにおいて、個人情報とは生存する個人に関する情報であって、氏名、生年月日、住所、電話番号、メールアドレス等、特定の個人を識別することができるものをいいます。
          </div>
          <h2 className="privacy-h2 text-xl md:text-2xl mt-10 mb-5 p-3">
            個人情報の管理
          </h2>
          <div>
            お客様からお預かりした個人情報は、不正アクセス、紛失、漏えい等が起こらないよう、慎重かつ適切に管理します。
          </div>
          <h2 className="privacy-h2 text-xl md:text-2xl mt-10 mb-5 p-3">
            個人情報の利用目的
          </h2>
          <div>
            当サイトでは、お客様からのお問い合わせやサービスへのお申し込み等を通じて、お客様の氏名、生年月日、住所、電話番号、メールアドレス等の個人情報をご提供いただく場合があります。その場合は、以下に示す利用目的のために、適正に利用するものと致します。
            <div className="privacy-list px-10 py-4 mx-4 my-10">
              <ul>
                <li className="privacy-listli">
                  お客様からのお問い合わせ等に対応するため。
                </li>
                <li className="privacy-listli">
                  お客様からお申し込みいただいたサービス等の提供のため。
                </li>
                <li className="privacy-listli">
                  メールマガジン等の配信、セミナーやイベントのご案内等のため。
                </li>
                <li className="privacy-listli">
                  当サイトが実施するアンケートへのご協力のお願いのため。
                </li>
                <li className="privacy-listli">
                  商品や景品、プレゼント等の発送のため。
                </li>
                <li className="privacy-listli">
                  当サイトのサービス向上・改善、新サービスを検討するための分析等を行うため。
                </li>
                <li className="privacy-listli">
                  個人を識別できない形で統計データを作成し、当サイトおよびお客様の参考資料とするため。
                </li>
              </ul>
            </div>
          </div>
          <h2 className="privacy-h2 text-xl md:text-2xl mt-10 mb-5 p-3">
            個人情報の第三者提供
          </h2>
          <div>
            お客様からお預かりした個人情報を、個人情報保護法その他の法令に基づき開示が認められる場合を除き、ご本人様の同意を得ずに第三者に提供することはありません。
          </div>
          <h2 className="privacy-h2 text-xl md:text-2xl mt-10 mb-5 p-3">
            個人情報の開示・訂正・削除について
          </h2>
          <div>
            お客様からお預かりした個人情報の開示・訂正・削除をご希望の場合は、ご本人様よりお申し出ください。適切な本人確認を行った後、速やかに対応させていただきます。
          </div>
          <h2 className="privacy-h2 text-xl md:text-2xl mt-10 mb-5 p-3">
            Cookie（クッキー）について
          </h2>
          <div className="mb-10">
            Cookie（クッキー）とは、お客様のサイト閲覧履歴を、お客様のコンピュータにデータとして保存しておく仕組みです。
          </div>
          <div className="mb-10">
            当サイトでは、第三者配信事業者である「Googleアドセンス、A8.net、もしもアフィリエイト、バリューコマース、afb」を利用しております。第三者配信事業者は、Cookieを使用することにより、お客様の過去のアクセス情報に基づいて、適切な広告を配信する場合があります。
          </div>
          <div className="mb-10">
            お客様は、Google広告設定から、Cookieを使用したパーソナライズ広告を無効にすることができます。なお、Cookieに保存されている情報からお客様個人を特定することはできません。
          </div>
          <div className="mb-10">
            また、当サイトは、Amazon.co.jpを宣伝しリンクすることによってサイトが紹介料を獲得できる手段を提供することを目的に設定されたアフィリエイトプログラムである「Amazonアソシエイト・プログラム」および「楽天アフィリエイト」の参加者です。
          </div>
          <h2 className="privacy-h2 text-xl md:text-2xl mt-10 mb-5 p-3">
            アクセス解析ツールについて
          </h2>
          <div className="mb-10">
            当サイトは、Googleが提供するアクセス解析ツール「Googleアナリティクス」を利用しています。Googleアナリティクスは、Cookieを使用することでお客様のトラフィックデータを収集しています。
          </div>
          <div>
            お客様はブラウザの設定でCookieを無効にすることで、トラフィックデータの収集を拒否することができます。なお、トラフィックデータからお客様個人を特定することはできません。詳しくはGoogleアナリティクス利用規約をご確認ください。
          </div>
          <h2 className="privacy-h2 text-xl md:text-2xl mt-10 mb-5 p-3">
            本ポリシーの変更
          </h2>
          <div>
            当サイトは、法令の制定、改正等により、本ポリシーを適宜見直し、予告なく変更する場合があります。本ポリシーの変更は、変更後の本ポリシーが当サイトに掲載された時点、またはその他の方法により変更後の本ポリシーが閲覧可能となった時点で有効になります。
          </div>
          <h1 className="text-2xl md:text-4xl mt-20 mb-10 bg-gold-100 text-white p-4">
            著作権
          </h1>
          <div className="mb-10">
            本ウェブサイトに掲載されている文章、画像、イラストなどの全てのコンテンツは、管理者およびその提供元が所有しております。
          </div>
          <div className="mb-10">
            書面による許可なく、個人的な目的以外でコピー、転載等は固くお断りさせていただきます。
          </div>
          <div>
            情報をご紹介いただく際には、著作権法上認められた正しい引用方法で行い、当サイトへのリンク掲載をお願いいたします。
          </div>
          <h1 className="text-2xl md:text-4xl mt-20 mb-10 bg-gold-100 text-white p-4">
            免責事項
          </h1>
          <div className="mb-10">
            当サイトの情報は、当サイト管理者が独学で学んだ知識の他、体験、感想などが含まれます。いずれの情報も専門的な知識は持っておりませんので、その正確性や安全性を保証するものではありません。
          </div>
          <div className="mb-10">
            当サイトのご利用につき発生した又は当該情報に基づき行われた行為により発生した、いかなるトラブル・損失・損害に対しても、一切の責任を負わないものといたします。
          </div>
          <div className="mb-10">
            当サイトに掲載されているウェブサイトやソフトウェアの合法性、正確性、道徳性、最新性、適切性、著作権の許諾や有無など、その内容については一切の保証をいたしかねます。
          </div>
          <div>
            当サイトからリンクやバナーなどによって他のサイトに移動された場合、移動先サイトで提供される情報、サービス等についてご来訪者様ご自身の責任において行ってくださいますようお願いいたします。
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default privacy;
