import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { useRouter } from "next/router";
import { format } from "date-fns";
import { useState, useEffect } from "react";
import { db } from "../public/src/firebase-config";
import { collection, getDocs, query, where } from "firebase/firestore";
import ProductDetailCard from "../components/ProductDetailCard";
import ChooseBrand from "../components/ChooseBrand";

const Productdetail = ({ searchResult }) => {
  const router = useRouter();
  const { img } = router.query;

  const [products, setProducts] = useState([]);
  const productsCollectionRef = collection(db, "products");

  const chooseProduct = query(
    productsCollectionRef,
    where("brand", "not-in", ["アクア", "美容液"])
  );

  useEffect(() => {
    const getProducts = async () => {
      const data = await getDocs(chooseProduct);

      let product = data.docs.map((doc) => ({ ...doc.data(), id: doc.id }));
      if (img) {
        product = product.filter((output, index) => {
          return output.img.includes(img);
        });
      }
      setProducts(product);
    };
    getProducts();
  }, [router.query.img]);
  console.log(products);

  return (
    <div>
      <Head>
        <title>Rikejo Cosme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <ProductCard /> */}
      <Header />

      <main className="flex">
        <section className="flex-grow pt-14 px-6">
          {/* <p className="text-tx">
            300+ Stays - {range}- for {noOfGuests} guests
          </p> */}

          <h1 className="text-3xl font-semibold mt-2 mb-6">
            {/* 「{categorySmall}」 を含む検索結果 */}
          </h1>

          <div className="hidden sm:inline-flex mb-5 space-x-3 text-gray-800 whitespace-nowrap">
            <ChooseBrand />
          </div>

          <div className="flex flex-col">
            {products.map(
              ({
                img,
                manufacture,
                brand,
                product,
                allIngredientName,
                categorySmall,
                price,
                capacity,
                unit,
                star_point,
              }) => (
                <ProductDetailCard
                  key={img}
                  img={img}
                  manufacture={manufacture}
                  brand={brand}
                  allIngredientName={allIngredientName}
                  categorySmall={categorySmall}
                  product={product}
                  price={price}
                  capacity={capacity}
                  unit={unit}
                  star_point={star_point}
                />
              )
            )}
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default Productdetail;
